paths:
  /api/admin/site:
    post:
      summary: Create a site
      tags:
        - Sites

      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Surabaya - Site A
                address:
                  type: string
                  example: Jalan Mastrip No 40, Surabaya
                city:
                  type: string
                  example: Surabaya
                province:
                  type: string
                  example: Jawa Timur
                latitude:
                  type: number
                  format: double
                  example: -7.321725109341672
                longitude:
                  type: number
                  format: double
                  example: 112.70984636375198

      responses:
        '200':
          description: Request confirmation
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: Site created
                  data:
                    type: object
                    properties:
                      name:
                        type: string
                        example: Surabaya - Site A

    get:
      parameters:
      - in: query
        name: page
        schema:
          type: integer
          description: Which page to show
      - in: query
        name: limit
        schema:
          type: integer
          description: Number of site to return
      summary: Get all site information and total count
      tags:
        - Sites

      responses:
        '200':
          description: List of sites
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: Sites retrieved
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        sites:
                          type: array
                          items:
                            type: object
                            properties:
                              id:
                                type: number
                                example: 1
                              name:
                                type: string
                                example: Surabaya - Site A
                              image:
                                type: string
                                example: imagelink
                              address:
                                type: string
                                example: Jalan Mastrip No 40, Surabaya
                              latitude:
                                type: number
                                format: double
                                example: -7.321725109341672
                              longitude:
                                type: number
                                format: double
                                example: 112.70984636375198
                      paging:
                        type: object
                        properties:
                          size:
                            type: number
                            example: 1
                          total_page:
                            type: number
                            example: 5
                          current_page:
                            type: number
                            example: 1

  /api/admin/site/{id}:
    get:
      parameters:
        - in: path
          name: id
          schema:
            type: integer
            description: Site's id to search
          required: true
      summary: Get a specific site information
      tags:
        - Sites

      responses:
        '200':
          description: Site information
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: Site retrieved
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 1
                      name:
                        type: string
                        string: "Jakarta Utara - Site A"
                      city:
                        type: string
                        example: "Jakarta Utara"
                      address:
                        type: string
                        example: "Jl. Industri No.123, Jakarta Utara"
                      province:
                        type: string
                        example: "DKI Jakarta"
                      operators:
                        type: integer
                        example: 3
                      status:
                        type: string
                        enum: ["ACTIVE", "MAINTENANCE", "INACTIVE"]
                        example: "ACTIVE"
                      lastReport:
                        type: string
                        example: "2 hours ago"
                      createdAt:
                        type: string
                        format: date-time
                        example: "2024-01-01T00:00:00Z"
                      updatedAt:
                        type: string
                        format: date-time
                        example: "2024-01-27T08:30:00Z"

    patch:
      parameters:
        - in: path
          name: id
          schema:
            type: integer
            description: Site's id to update
          required: true
      summary: Update a site
      tags:
        - Sites

      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Surabaya - Site A Updated
                city:
                  type: string
                  example: Surabaya Timur
                address:
                  type: string
                  example: Jalan Industri No 40, Surabaya Timur
                province:
                  type: string
                  example: Jawa Timur
                status: 
                  type: string
                  enum: ["ACTIVE", "MAINTENANCE", "INACTIVE"]
                  example: MAINTENANCE
      responses:
        '200':
          description: Request confirmation
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: Site updated successfully
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 1
                      name:
                        type: string
                        example: Surabaya - Site A Updated
                      city:
                        type: string
                        example: Surabaya Timur
                      address:
                        type: string
                        example: Jalan Industri No 40, Surabaya Timur
                      province:
                        type: string
                        example: Jawa Timur
                      operators:
                        type: number
                        example: 3
                      status: 
                        type: string
                        enum: ["ACTIVE", "MAINTENANCE", "INACTIVE"]
                        example: MAINTENANCE
                      lastReport:
                        type: string
                        example: 2 hours ago
